### ISSUE TITLE
Multiple AWS accounts?

### ISSUE THREAD

**Issue by jyjohnson** [AppliedTrust/traildash#26]
This project looks really cool. I'm guessing it would take a lot of work to support multiple accounts? For example, let the user select via drop-down which account to view.

Thanks.

**Comment by nmcclain** [comment]
It supports multiple accounts today, but it only supports using a single set of AWS credentials.  So that means you need to configure each account's CloudTrail settings to send notifications to a single SQS queue and S3 bucket.  CloudTrail stores the logs in S3 beneath an account ID, so it works well with many accounts.

In Kibana, you can easily add a filter based on account ID.
