### ISSUE TITLE
Standalone Kibana dashboard?

### ISSUE THREAD

**Issue by imphasing** [AppliedTrust/traildash#34]
We already have infrastructure for ingesting cloudtrail logs into Elasticsearch. Would it be possible to provide a standalone export of the dashboard JSON so people with existing infrastructure can consume this dashboard?

**Comment by nmcclain** [comment]
That export is here: https://github.com/AppliedTrust/traildash/blob/master/assets/CloudTrail.json

Also, please note that Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
